### ISSUE TITLE
Carthage issues: mutually incompatible requirements

### ISSUE THREAD

**Issue by kohlab** [mapbox/mapbox-directions-swift#438]
I find it continually difficult to upgrade my project to the latest Mapbox libraries. The latest attempt yields this error:

```
dylan@Moe client % carthage update --platform ios --no-use-binaries --new-resolver
*** Downloading binary-only framework Mapbox-iOS-SDK at "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json"
*** Fetching mapbox-navigation-ios
*** Fetching mapbox-directions-swift
*** Fetching MapboxGeocoder.swift
Could not pick a version for github "mapbox/mapbox-directions-swift", due to mutually incompatible requirements:
	~> 0.33.0
	~> 0.31.0 (github "mapbox/mapbox-navigation-ios")

```

This is using the following Cartfile:

```
github "mapbox/mapbox-directions-swift" ~> 0.33
github "mapbox/MapboxGeocoder.swift" ~> 0.12
github "mapbox/mapbox-navigation-ios" ~> 0.40
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" == 5.9.0
```

What's going on here and why in general might it be so difficult to use the latest Mapbox versions?

Since this latest attempt failed, I'll revert to the last version that was stable for me:

```
github "mapbox/mapbox-directions-swift" ~> 0.30
github "mapbox/MapboxGeocoder.swift" ~> 0.12
github "mapbox/mapbox-navigation-ios" ~> 0.38.1
binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" == 5.5.0

```

**Comment by Udumft** [comment]
Hello @kohlab!
This error comes from dependencies conflict with `mapbox-directions-swift` specified in the `Cartfile` and this same lib used as sub-dependency in `mapbox-navigation-ios`. Same thing goes to `Mapbox-iOS-SDK`: it's also a sub-dependency in `mapbox-navigation-ios`.
In general, you don't have to explicitly specify those to avoid that kind of conflicts, and you'll still get all the same libs downloaded.
In fact, your `Cartfile` could look like this and have exact all the same deps:
```
github "mapbox/MapboxGeocoder.swift" ~> 0.12
github "mapbox/mapbox-navigation-ios" ~> 0.40
```

However, If you absolutely need `mapbox-directions-swift v0.33` and `mapbox-navigation-ios v0.40` at the same time, unfortunately `Carthage` cannot do that for you automatically, and you'll have to deal with some dependencies conflicts in your own project. 
You could do the following:
* configure `Cartfile` as above

**Comment by Udumft** [comment]
Hello @kohlab!
This error comes from dependencies conflict with `mapbox-directions-swift` specified in the `Cartfile` and this same lib used as sub-dependency in `mapbox-navigation-ios`. Same thing goes to `Mapbox-iOS-SDK`: it's also a sub-dependency in `mapbox-navigation-ios`.
In general, you don't have to explicitly specify those to avoid that kind of conflicts, and you'll still get all the same libs downloaded.
In fact, your `Cartfile` could look like this and have exact all the same deps:
```
github "mapbox/MapboxGeocoder.swift" ~> 0.12
github "mapbox/mapbox-navigation-ios" ~> 0.40
```

However, If you absolutely need `mapbox-directions-swift v0.33` and `mapbox-navigation-ios v0.40` at the same time, unfortunately `Carthage` cannot do that for you automatically, and you'll have to deal with some dependencies conflicts in your own project. 
You could do the following:
* configure `Cartfile` as above
* run `carthage update ...`
* go to `<your_project>/Carthage/Checkouts/mapbox-navigation-ios` and edit `Cartfile` to contain 
```github "mapbox/mapbox-directions-swift" ~> 0.33```
* run `carthage update --platform ios` from `<your_project>/Carthage/Checkouts/mapbox-navigation-ios` folder

This will attempt to build `mapbox-navigation-ios` with another version of `directions`, but be aware that this is **not a stable solution** and **was not intended to be used this way**! Any bug/crash/issue may occur in this combination and you should do that on your **own risk**. 
Actually, this is the direct answer to your question " why in general might it be so difficult to use the latest Mapbox versions?" - dependencies versions cannot be updated automatically because of stability and compatibility issues. And to avoid those, we encourage you to not explicitly list all sub-dependencies and only include the required `mapbox-navigation-ios` one.

**Comment by kohlab** [comment]
Hi @Udumft!

Your answer solved the issue entirely. I dropped `mapbox-directions-swift` from my Cartfile and all is well! Clearly it was redundant and unnecessary.

As an aside, I'm relatively new to Carthage so am not sure how you determined there were dependency conflicts. Can you fill me in?

Many thanks for getting me up and running with the latest again.

**Comment by Udumft** [comment]
I'm glad I could help :)
Actually, the error message speaks for itself:
```
Could not pick a version for github "mapbox/mapbox-directions-swift", due to mutually incompatible requirements:
	~> 0.33.0
	~> 0.31.0 (github "mapbox/mapbox-navigation-ios")
```
In brackets it points to the repo that has conflicting sub-dependency. You can find it in `<your_project>/Carthage/Checkouts/mapbox-navigation-ios/Cartfile` and, as you could guess, this is a recursive process.


> I dropped mapbox-directions-swift from my Cartfile and all is well!

I would also suggest removing `binary "https://www.mapbox.com/ios-sdk/Mapbox-iOS-SDK.json" == 5.9.0` because it is also already included inside `mapbox-navigation-ios`.

**Comment by kohlab** [comment]
Wow, in hindsight it’s obvious what the problem was, thank you. ...Just curious, how’d you know the binary was redundant? Where do I see a package's dependencies?

**Comment by Udumft** [comment]
`mapbox-navigation-ios`, just like your own project, has a `Cartfile` where you can find it's dependencies. This applies to all dependencies you checkout using `Carthage` as source files.

**Comment by kohlab** [comment]
Now everything makes total sense. Thank you!
