### ISSUE TITLE
Route exceeds maximum distance limitation

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-directions-swift#544]
Mapbox-iOS-SDK 6.3.0
MapboxDirections 1.2.0
MapboxNavigation 1.2.0

I get this error when using `Directions.shared.calculateRoutes(matching: options)`
The distance is from London to Leeds (194.9 miles https://www.google.com/search?q=distance+london+leeds&oq=distance+london+leeds&aqs=chrome..69i57j0i22i30.2842j0j7&sourceid=chrome&ie=UTF-8)

For options, I set profile identifier  as automobile (but I also tested out with automobileAvoidingTraffic)
I searched in the documentation for the limitation but I couldn't find out what is the value.

Can I increase somehow this limitation? What is the best approach regarding options setup, for those kinds of situations?

**Comment by 1ec5** [comment]
Hi, [the distance limit](https://docs.mapbox.com/api/navigation/directions/#directions-api-restrictions-and-limits) is enforced by the Directions API on the server side, since it is possible for Mapbox to increase the limit on a per-customer basis. That said, the limit should be orders of magnitude higher than the distance from London to Leeds by car. Can you provide the exact coordinates you used as waypoints? Thanks!
