### ISSUE TITLE
Route object encode and decode

### ISSUE THREAD

**Issue by nastasiupta** [mapbox/mapbox-directions-swift#555]
I want to save the object Route object to server, and recreate the Route object with the data from server in a future session.
I'm encoding the data as follows:
```
let encoder = JSONEncoder()
let legJson = try? encoder.encode(route)
data["json"] = legJson
```
I saw the following example from documentation to decode:
https://docs.mapbox.com/ios/navigation/examples/route-deserialization/

```
let legData = data["json"] as? [String: Any]
let origin = startPlace.location.coordinate2D
let destination = destinationPlace.location.coordinate2D
let routeOptions = NavigationRouteOptions(coordinates: [origin, destination])
let jsonData = try! JSONSerialization.data(withJSONObject: legData)
let decoder = JSONDecoder()
decoder.userInfo[.options] = routeOptions
let route: Route? = try? decoder.decode(Route.self, from: jsonData)
```
Route object is nil after this... 
Also another thing to mention in Firestore I can see the data type as Blob

Versions:
  pod 'Mapbox-iOS-SDK', '6.3.0'
  pod 'MapboxDirections', '1.2.0'
  pod 'MapboxNavigation', '1.4.1'
Xcode: 12.5.1

* On an older version of Mapbox we had a property for Route object that could provide a JSON... but as I see during the SDKs upgrade, this one was removed. Is there another approach to get the JSON for Route object?

**Comment by 1ec5** [comment]
> Route object is nil after this...

Please replace the `try?` with a `do`/`catch` block; the caught error will indicate what the decoding implementation thinks is malformed about the JSON data.

>     On an older version of Mapbox we had a property for Route object that could provide a JSON... but as I see during the SDKs upgrade, this one was removed. Is there another approach to get the JSON for Route object?

JSONDecoder is the way to convert JSON to a Route. There’s also a convenience initializer that takes each individual piece of data in structured form.

**Comment by nastasiupta** [comment]
@1ec5  I printed out some details...

`        let origin = startPlace.location.coordinate2D
        let destination = destinationPlace.location.coordinate2D
        let routeOptions = NavigationRouteOptions(coordinates: [origin, destination])
        let jsonData = try! JSONSerialization.data(withJSONObject: legData)
        let decoder = JSONDecoder()
    
        decoder.userInfo[.options] = routeOptions
        do {
            let route: Route? = try decoder.decode(Route.self, from: jsonData)
        } catch let error {
            print(jsonData.count)
            print(error.localizedDescription)
        }`

print(jsonData.count)
print(error.localizedDescription)

3306228
The data couldn’t be read because it is missing.
2192811
The data couldn’t be read because it is missing.
347050
The data couldn’t be read because it is missing.
1243495
The data couldn’t be read because it is missing.

I have 4 different Route objects and looks like it fails for all of them...

**Comment by nastasiupta** [comment]
@S2Ler  @1ec5 
Also, I wanted to ask why the JSON property was removed from the Route object and if the JSON property will be removed from Android SDK as well.

**Comment by 1ec5** [comment]
> No value associated with key CodingKeys(stringValue: "legs", intValue: nil) ("legs").", underlyingError: nil))

This means the JSON object you tried to decode is missing a `legs` property. When you decode a Route, it needs to match the format of the [Directions API](https://docs.mapbox.com/api/navigation/directions/#route-object) response.

> Also, I wanted to ask why the JSON property was removed from the Route object

#382 rewrote the library in pure Swift, enabling us to take advantage of the Swift standard library’s Codable protocol instead of maintaining custom JSON parsing code that was rife with implicitly unwrapped optionals. `Route(json:legs:distance:expectedTravelTime:coordinates:speechLocale:options:)` and the `json` property were entirely redundant to Codable at that point, and the `json` property took up significant memory, so we removed them. To convert a Route object to JSON, use JSONEncoder.

> the JSON property will be removed from Android SDK as well.

Java doesn’t have an analogue to Codable, so the considerations above don’t apply. I’m unaware of any plans to change JSON facilities in mapbox-java. If that ever happens, you’ll see it take place in that repository, and I’m sure there will be a suitable replacement, because the navigation SDK depends on the ability to round-trip JSON for various tasks.
