### ISSUE TITLE
Command line tool should accept multiple configurations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-directions-swift#729]
The command line tool should accept multiple configuration files or a configuration file plus a URL, merging the various options into a single request. It currently accepts only one configuration file or a URL, which makes it awkward to describe what the argument should be.

/ref https://github.com/mapbox/mapbox-directions-swift/pull/728#discussion_r950625807
/cc @mapbox/navigation-ios

**Comment by jill-cardamon** [comment]
Closing this ticket since this might not be an improvement. While this addition would bring clarity to the option description and make it possible for the user to pass multiple paths/URLs or specify the same option multiple times, the behavior might be unexpected and unclear to users (will the tool send multiple requests? when will it fail?).
